## Data Science with Python

### NumPy

In [3]:
!pip install numpy

In [5]:
#to import numpy
import numpy as np

In [9]:
#recall a list
zBList = [1 ,2, 3]
print(zBList)


[1, 2, 3]


#### Creating NumPy Arrays

In [11]:
#CREATING ARRAYS

myArray = np.array([1, 2, 3])
print(myArray)

[1 2 3]


In [23]:
#CREATING ARRAYS
#Creating a zero-dimensional array (also called Scalers)

zero_dim = np.array(34)                                                    #0D array: a single number or item
print(zero_dim)
print()
print(zero_dim.ndim)                                                       #to check dimensions

34

0


In [25]:
#CREATING ARRAYS
#Creating a one-dimensional array

one_dim = np.array([1, 3, 5])                                             #1D array: a list of numbers or items
print(one_dim)
print()
print(one_dim.ndim)                                                       #to check dimensions

[1 3 5]

1


In [27]:
#CREATING ARRAYS
#Creating a two-dimensional array

two_dim = np.array([[1, 3, 5], [2, 4, 6]])                                #2D array: a list of one or more 1D arrays
print(two_dim)
print()
print(two_dim.ndim)                                                       #to check dimensions

[[1 3 5]
 [2 4 6]]

2


In [31]:
#CREATING ARRAYS
#Creating a three-dimensional array

three_dim = np.array([[[1, 3, 5], [2, 4, 6], [7, 8, 9]]])                                  #3D array: a list of one or more 2D arrays
print(three_dim)
print()
print(three_dim.ndim)   

[[[1 3 5]
  [2 4 6]
  [7 8 9]]]

3


In [43]:
#CREATING ARRAYS
#Creating a three-dimensional array

three_dim = np.array([[[1, 3, 5], [2, 4, 6]], [[7, 8, 9], [10, 11, 12]]])                   #3D array: a list of one or more 2D arrays
print(three_dim)
print()
print(three_dim.ndim)                                                                      #to check dimensions       

[[[ 1  3  5]
  [ 2  4  6]]

 [[ 7  8  9]
  [10 11 12]]]

3


#### Indexing NumPy Arrays

In [69]:
#INDEXING ARRAYS


#create an array

myArray_oneD = np.array([10, 20, 30, 40, 50])                   
#print(myArray_oneD)
#print(myArray_oneD.ndim)  

#accessing the first element in an array 
myArray_oneD[0]                                                                                

10

In [75]:
#INDEXING ARRAYS


#create an array

myArray_twoD = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])                   
#print(myArray_twoD)
#print(myArray_twoD.ndim)  

#accessing the first element in an array 
myArray_twoD[0]  

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


array([1, 2, 3, 4, 5])

In [82]:
#INDEXING ARRAYS

#accessing the fourth element in the second array of the 2D array 

myArray_twoD[1, 3]                                                          #1:index of the 2nd array, and 3: index of the 4th element of the 2nd array

9

#### Slicing NumPy Arrays

In [104]:
#SLICING ARRAYS

myArray_oneD = np.array([10, 20, 30, 40, 50])                   

#accessing a range in an array 
myArray_oneD[0:4]                                      #start index: 0 is the 1st element, and, end index 4: index of the 4th element of the array

array([10, 20, 30, 40])

In [88]:
#SLICING ARRAYS

myArray_oneD = np.array([10, 20, 30, 40, 50])                   

#accessing the first 4 elements in an array with a step size of 2
myArray_oneD[0:4:2]                            

array([10, 30])

In [102]:
#SLICING ARRAYS

myArray_twoD = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])                    

#accessing the first 4 elements in an array 
myArray_twoD[1,0:4]                                     

#array index: 1 is the second array
#start index: 0 is the 1st element #end index: 4 is the 4th element of the second array

array([6, 7, 8, 9])

In [106]:
#SLICING ARRAYS

myArray_twoD = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])                    

#accessing the first 4 elements in an array with a step size of 2
myArray_twoD[1,0:4:2]                                     

#array index: 1 is the second array
#start index: 0 is the 1st element #end index: 4 is the 4th element of the second array

array([6, 8])

#### Copying and Viewing Arrays

In [122]:
#COPYING ARRAYS

#create an array

originalArray = np.array([1, 2, 3, 4, 5])

#to copy
copiedArray = originalArray.copy()
print(copiedArray)                                               #changes made in the original array does not affect the copied array

[1 2 3 4 5]


In [124]:
#VIEWING ARRAYS

#create an array

originalArray = np.array([1, 2, 3, 4, 5])

#to view
viewedArray = originalArray.view()
print(viewedArray)                                             #changes made in the viewed array does affect the original array

[1 2 3 4 5]


#### Shape of an Array and Reshaping Arrays

In [147]:
#SHAPE OF AN ARRAY

#check the shape
mArray_1D = np.array([10, 20, 30, 40, 50])
print(mArray_1D.shape)

(5,)


In [142]:
#SHAPE OF AN ARRAY

#check the shape
myArray_2D = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [12, 13, 14, 15, 16]]) 
print(myArray_2D.shape)

(3, 5)


In [ ]:
#SHAPE OF AN ARRAY

#NB:checking the shape of an inhomogeneous array = Error message

#myArray_ihD = np.array([[1, 2, 3], [6, 7, 8, 9], [12, 13, 14, 15, 16]]) 
#print(myArray_ihD.shape)

#this returns an error message because its inhomogeneous

In [153]:
#RESHAPING AN ARRAY

#reshape such that the outermost dimension will have two arrays, each containing five elements.

m_Array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(m_Array)
print(m_Array.shape)
print()

#Dammy: similar to converting 1D to 2D
newm_Array = m_Array.reshape(2,5) 
print(newm_Array)
print()
print(newm_Array.shape)

[ 10  20  30  40  50  60  70  80  90 100]
(10,)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]

(2, 5)


In [155]:
#RESHAPING AN ARRAY

#reshape such that the outermost dimension will have TWO arrays that would hold THREE arrays, each containing 2 elements.

m_Array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120])
print(m_Array)
print(m_Array.shape)
print()

#Dammy: similar to converting 1D to 3D
newm_Array = m_Array.reshape(2, 3, 2) 
print(newm_Array)
print()
print(newm_Array.shape)

#array index: 2 is the array, 3 is the number of 1D array in each; 2 is the number of element per 1D array

[ 10  20  30  40  50  60  70  80  90 100 110 120]
(12,)

[[[ 10  20]
  [ 30  40]
  [ 50  60]]

 [[ 70  80]
  [ 90 100]
  [110 120]]]

(2, 3, 2)


#### Basic Operations in NumPy Arrays

In [159]:
#recall in list
#you can generate a range

print(list(range(1, 10)))

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [163]:
#GENERATING A RANGE

#you can generate a range using: ARANGE function
#Syntax: rangeArray = np.array(start, stop, step)

m_Array = np.arange(0, 10, 2)
print(m_Array)
print(m_Array.shape)

[0 2 4 6 8]
(5,)


In [171]:
#GENERATING A RANGE

#you can generate a range using: ARANGE function
#Syntax: rangeArray = np.array(start, stop, step)

m_Array = np.arange(101, 105, 1)
print(m_Array)
print(m_Array.shape)

[101 102 103 104]
(4,)


In [175]:
#BASIC MATHEMATICAL OPERATIONS

#Addition

a = np.array([10, 20, 30, 40])
b = np.array([5, 10, 15, 20])


print(a + b)

[15 30 45 60]


In [181]:
#BASIC MATHEMATICAL OPERATIONS

#Subtraction

print(a - b)

[ 5 10 15 20]


In [183]:
#BASIC MATHEMATICAL OPERATIONS

#Multiplication

print(a * b)

[ 50 200 450 800]


In [185]:
#BASIC MATHEMATICAL OPERATIONS

#Division

print(a / b)

[2. 2. 2. 2.]


In [187]:
#BASIC MATHEMATICAL OPERATIONS

#Modulus

print(a % b)

[0 0 0 0]


In [191]:
#BASIC MATHEMATICAL OPERATIONS

#Multiply all the elements in an array by a number

a = np.array([10, 20, 30, 40])
print(a)
print()
print(a * 2)

[10 20 30 40]

[20 40 60 80]


In [193]:
#BASIC MATHEMATICAL OPERATIONS

#square all the elements in an array by a number

a = np.array([10, 20, 30, 40])
print(a)
print()
print(a ** 2)

[10 20 30 40]

[ 100  400  900 1600]


In [195]:
#BASIC MATHEMATICAL OPERATIONS

#square root of an array

a = np.array([10, 20, 30, 40])
print(a)
print()
print(np.sqrt(a))

[10 20 30 40]

[3.16227766 4.47213595 5.47722558 6.32455532]


#### Data Analytics Operations in NumPy Arrays

In [204]:
#Create an Array

m_1DArray = np.array([10, 20, 30, 40])
m_2DArray = np.array([[4, 8, 12, 16], [2, 4, 6, 8]])

In [206]:
#SUMMATIONS
#in 1D

print(sum(m_1DArray))                                             #sums all elements in the 1D array to give a number

100


In [208]:
#SUMMATIONS
#in 2D

print(sum(m_2DArray))                                             #adds the two 1D arrays in the 2D array to give an array

[ 6 12 18 24]


In [212]:
#SUMMATIONS

#using SUM function
#in 1D

print(m_1DArray.sum())                                             #gives a number

100


In [214]:
#SUMMATIONS

#using SUM function
#in 2D

print(m_2DArray.sum())                                             #sums all elements in the 2D array to give a number

60


In [218]:
#MINIMUM

#in 1D
print(m_1DArray.min())

print()

#in 2D
print(m_2DArray.min())                                            

10

2


In [220]:
#MAXIMUM

#in 1D
print(m_1DArray.max())

print()

#in 2D
print(m_2DArray.max())  

40

16


In [232]:
#SUMMATION across rows and columns in arrays

#in 2D

m_2DArray = np.array([[4, 8, 12, 16], [2, 4, 6, 8], [5, 10, 15, 20]])

print(m_2DArray) 
print()

#to sum across rows
print(m_2DArray.sum(axis = 1))
print()

#to sum across columns
print(m_2DArray.sum(axis = 0))

[[ 4  8 12 16]
 [ 2  4  6  8]
 [ 5 10 15 20]]

[40 20 50]

[11 22 33 44]


In [234]:
#MEAN across rows and columns in arrays

#in 2D

m_2DArray = np.array([[4, 8, 12, 16], [2, 4, 6, 8], [5, 10, 15, 20]])

print(m_2DArray) 
print()

#to find mean across rows
print(m_2DArray.mean(axis = 1))
print()

#to find mean across columns
print(m_2DArray.mean(axis = 0))

[[ 4  8 12 16]
 [ 2  4  6  8]
 [ 5 10 15 20]]

[10.   5.  12.5]

[ 3.66666667  7.33333333 11.         14.66666667]


#### Project: Generate Random Numbers in a NumPy Array
##### Description - In this task, students will create a NumPy array filled with random numbers. They will be required to specify the size of the array and set the range for the random values.9:'D'

In [304]:
#Import the necessary library
import numpy as np

#Prompt the user to enter the number of rows for the array
n_rows = int(input("Enter the desired number of rows for the array: "))
print()

#Prompt the user to enter the number of columns for the array            
n_columns = int(input("Enter the desired number of columns for the array: "))
print()

#Prompt the user to enter the minimum value for random numbers            
min_value = int(input("Enter a desired minimum value: "))
print()

#Prompt the user to enter the maximum value for random numbers            
max_value = int(input("Enter a desired maximum value: "))
print()

#Generate a NumPy array with dimensions (n_rows x n_columns) and populate it with random values between min_value and max_value
def gen_randArray(n_rows, n_columns, min_value, max_value):
    #Numpy random number syntax: np.random.randint(start, stop, size) 
    randArray = np.random.randint (min_value, max_value + 1, size = (n_rows, n_columns))
    return randArray
print()

#Print the generated array to the console
my_randArray = gen_randArray(n_rows, n_columns, min_value, max_value)
print("The randomly generated numbers in a NumPy:\n", my_randArray)
print()

print(my_randArray.shape)
print()

print(my_randArray.ndim)
print()

print("Well done! Dami")

Enter the desired number of rows for the array:  4


Enter the desired number of columns for the array:  6


Enter a desired minimum value:  40


Enter a desired maximum value:  100




The randomly generated numbers in a NumPy:
 [[60 93 55 44 84 63]
 [61 40 47 51 81 95]
 [55 99 94 80 49 66]
 [42 62 80 94 49 70]]

(4, 6)

2

Well done! Dami
